### PR TITLE
Add Carthage support

### PR DESCRIPTION
**Pull request by mattprowse**
I've been happily using LetsMove in all of my Mac apps for years, and since I'm using Carthage to manage dependencies these days I thought it would be useful to add support for installing LetsMove using Carthage.

Adding Carthage support basically just involves adding a shared Framework target to the project (plus an umbrella header and a module map for the framework), which does unfortunately mean there are a lot of messy changes in the project file.

Additionally, since it makes sense for the shared framework to be named "LetsMove", I've renamed the test app target "LetsMove Test".

I've tried to change as little as possible to get this working, but I'm happy to make any changes necessary to help get this merged.

### CODE REVIEW

**Comment by andypotion** [comment]
I notice that deployment target has been changed to 10.6 from 10.5. Would it be possible to keep it at 10.5? Otherwise, we're going to have to update the version and note the change the in the readme.

**Comment by mattprowse** [comment]
Oh, sorry I completely forgot to mention that change! I set the deployment target for the framework target to 10.6 to avoid a linker warning:

`(/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/arc/libarclite_macosx.a(arclite.o)) was built for newer OSX version (10.6) than being linked (10.5)`

ARC is disabled on the framework target but that doesn't seem to stop Xcode from linking with libarclite unfortunately. My guess is that building for deployment on 10.5 is no longer officially supported when you're building against the 10.11 SDK with Xcode 7.

That said, other than the warning there isn't really any need to change the build target. And the warning doesn't seem to cause any problems, so it's probably not a big deal to just change change the deployment target back and put up with the warning being there.

Let me know which way you want to go and I'll update the PR with the changes ASAP.

**Comment by andypotion** [comment]
Having slept on it, it seems best that we do drop 10.5 support. Even with just 10.6, we're supporting 6 OS releases. I've updated the version to 1.21 and published to master. Thanks for the PR.

**Comment by mattprowse** [comment]
Great, thanks for reviewing this so quickly! Thanks too for writing LetsMove in the first place. As I say I've been using it for years in my apps; it's one of a handful of essentials that I use in every Mac app I write.

**Comment by mattprowse** [comment]
Sorry to be a pain, but any chance you could add a tag and a release for version 1.21? Installing from Carthage won't work without them. Thanks!

**Comment by andypotion** [comment]
I pushed a `v1.21` tag. But what do you mean by "release for version 1.21?"

**Comment by mattprowse** [comment]
Sorry, that's just my ignorance about how GitHub works. For some reason I thought releases and tags were separate. Everything looks to be working fine now that the v1.21 tag is there. Thanks!

**Pull request merged**
